Watching for file changes with StatReloader
[05/Aug/2025 18:17:41] "GET / HTTP/1.1" 200 39
Not Found: /favicon.ico
[05/Aug/2025 18:17:41] "GET /favicon.ico HTTP/1.1" 404 3450
[05/Aug/2025 18:17:45] "GET /swagger/ HTTP/1.1" 200 2211
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
view's ChatRoomRetrieveUpdateDestroyView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\contrib\auth\models.py", line 549, in __int__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\chat\views.py", line 27, in get_queryset
    return ChatRoom.objects.filter(Q(user1=self.request.user) | Q(user2=self.request.user))
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1503, in build_filter
    return self._add_q(
           ~~~~~~~~~~~^
        filter_expr,
        ^^^^^^^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000023BF25CBC50>.
view's ChatRoomRetrieveUpdateDestroyView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\contrib\auth\models.py", line 549, in __int__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\chat\views.py", line 27, in get_queryset
    return ChatRoom.objects.filter(Q(user1=self.request.user) | Q(user2=self.request.user))
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1503, in build_filter
    return self._add_q(
           ~~~~~~~~~~~^
        filter_expr,
        ^^^^^^^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000023BF25CBC50>.
view's ChatRoomRetrieveUpdateDestroyView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\contrib\auth\models.py", line 549, in __int__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\chat\views.py", line 27, in get_queryset
    return ChatRoom.objects.filter(Q(user1=self.request.user) | Q(user2=self.request.user))
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1503, in build_filter
    return self._add_q(
           ~~~~~~~~~~~^
        filter_expr,
        ^^^^^^^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000023BF25CBC50>.
[05/Aug/2025 18:17:45] "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
view's ChatRoomRetrieveUpdateDestroyView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\contrib\auth\models.py", line 549, in __int__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\chat\views.py", line 27, in get_queryset
    return ChatRoom.objects.filter(Q(user1=self.request.user) | Q(user2=self.request.user))
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1503, in build_filter
    return self._add_q(
           ~~~~~~~~~~~^
        filter_expr,
        ^^^^^^^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000023BF25CBC50>.
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 45, in get_operation
    responses = self.get_responses()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 180, in get_responses
    response_serializers = self.get_response_serializers()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 235, in get_response_serializers
    responses = self.get_default_responses()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 211, in get_default_responses
    default_schema = self.serializer_to_schema(default_schema) or ''
                     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'get_schema', serializer, {'field_inspectors': self.field_inspectors}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 49, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'field_to_swagger_object', field, {'field_inspectors': self.field_inspectors},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 140, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 109, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'subcategories' was declared on serializer CategorySerializer, but has not been included in the 'fields' option.
[05/Aug/2025 18:17:45] "GET /swagger/?format=openapi HTTP/1.1" 500 219505
Performing system checks...

System check identified no issues (0 silenced).
August 05, 2025 - 18:15:59
Django version 5.2.4, using settings 'config.settings'
Starting development server at http://127.0.0.1:8001/
Quit the server with CTRL-BREAK.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
